site_name: napari-nucleaizer
site_description: A GUI interface for training and prediction using the nucleAIzer nuclei detection method.
site_author: Ervin Tasnadi

theme: readthedocs

repo_url: https://github.com/etasnadi/napari-nucleaizer

pages:
- Home: index.md
